export PLATFORM=linux

# Compiler setup
export CC=g++
export CFLAGS=-W -Wall -Werror -std=c++11

RELEASE_CFLAGS=-O2
DEBUG_CFLAGS=-g -O0

ifeq ($(MODE),debug)
	CFLAGS+=$(DEBUG_CFLAGS)
else
	CFLAGS+=$(RELEASE_CFLAGS)
endif

# Tools
export AR=ar
export AR_FLAGS=rcs

# Environment variables
export INCLUDES_FLAG=-I
export LIBPATH_FLAG=-L
export LIBS_FLAG=-l
export OUTPUT_FLAG=-o
export GEN_OBJECT_FLAG=-c

# Platform specific libs
export LIBS=-lcaca -lwebp

include Makefile.common
