export PLATFORM=macos

# Compiler setup
export CC=clang
export CFLAGS=-W -Wall -Werror -std=c++11

RELEASE_CFLAGS=-O2
DEBUG_CFLAGS=-g -O0

ifeq ($(MODE),debug)
	CFLAGS+=$(DEBUG_CFLAGS)
else
	CFLAGS+=$(RELEASE_CFLAGS)
endif

# Tools
export AR=ar
export AR_FLAGS=rcs

include Makefile.common
