#Targets
NAME=engine_$(PLATFORM)_$(MODE)
TARGET=$(NAME).lib

# Compiler setup
INCLUDES+=/I include /I ../../lib/SDL/$(PLATFORM)/include

# Files
SOURCES=${wildcard src/*.cpp}
SOURCES+=${wildcard src/$(PLATFORM)/*.cpp}

OBJECTS=$(SOURCES:.cpp=.obj)

# Rules
.SUFFIXES: .cpp .obj

.cpp.obj:
	@echo "Aqui"
	$(CC) /c $< $(CFLAGS) $(INCLUDES) /Fo:$@ 

all: $(TARGET)

# Targets
$(TARGET): $(OBJECTS)
	$(AR) $(AR_FLAGS) $(OBJECTS) /OUT:$@
