#Targets
NAME=engine_$(PLATFORM)_$(MODE)
TARGET=lib$(NAME).a

# Compiler setup
INCLUDES=-Iinclude -I../../lib/SDL/$(PLATFORM)/include

# Files
SOURCES=${wildcard src/*.cpp}
SOURCES+=${wildcard src/$(PLATFORM)/*.cpp}

OBJECTS=$(SOURCES:.cpp=.o)

# Rules
.cpp.o:
	$(CC) -c $< -o $@ $(CFLAGS) $(INCLUDES)

all: $(TARGET)

# Targets
$(TARGET): $(OBJECTS)
	$(AR) $(AR_FLAGS) $@ $(OBJECTS)
