#!/bin/bash
#
# Clean all autogenerated files.
#

mode=$1

function clean()
{
    platform=`uname -a`

    if [[ "$platform" =~ "Linux" ]];
    then
        find . -name '*.o' -exec rm {} \;
        find . -name '*~' -exec rm {} \;
#    else
#        echo "Aqui 2";
#        platform="unknown";
    fi
}

# Main
echo "Cleaning up..."
clean
echo "Done"
