#!/bin/bash
#
# Clean all autogenerated files.
#

# Main
echo "Cleaning up..."
find . -name '*.o' -exec rm -f {} \;
find . -name '*.a' -exec rm -f {} \;
find . -name '*~' -exec rm -f {} \;
find . -name '*.obj' -exec rm -f {} \;
find . -name '*.lib' -exec rm -f {} \;
echo "Done"
